env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

language: python

sudo: true

python:
  - 3.6.9

cache: pip

install:
  - cp ./requirements.txt ./deps/
  - bash ./deps/installPythonLibs.sh

script:
  - flake8
  - python -m unittest

after_success:
  - (test $TRAVIS_PULL_REQUEST != "false") && exit 0
  - (test $TRAVIS_BRANCH != "master" && test $TRAVIS_BRANCH != "development") && exit 0
  - cd ./docker/
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  - export REPO=gvit/legion
  - docker build -f Dockerfile -t $REPO:$COMMIT . --no-cache
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - test $TRAVIS_BRANCH = "master" && docker tag $REPO:$COMMIT $REPO:latest
  - test $TRAVIS_BRANCH = "master" && docker push gvit/legion:latest
  - test $TRAVIS_BRANCH = "development" && docker tag $REPO:$COMMIT $REPO:development
  - test $TRAVIS_BRANCH = "development" && docker push gvit/legion:development
